### ISSUE TITLE
Is this repository a mirror/redistribution or the original source code?

### ISSUE THREAD

**Issue by takagiy** [ohac/tn_fnds#2]
Hello!
I'm interested in singing syntheses and the implementation of the resampler, tn_fnds and I found this repository named `tn_fnds`.

But I have some questions:
1. Is this repository a mirror or a redistributuon of the original code? Or are you Zteer-san, the original developer of tn_fnds?
1. Does the codes in this repository is updated as well as the latest release of tn_fnds (v0.0.9 at 2013/4/11)?
1. (optional) Could you tell me some helpful documentation about the implementation or the history of the “looping type” resampler such as tn_fnds?

Thank you, so much!

**Comment by ohac** [comment]
1. This is a redistributuon of the original code.
2. 2014/8/11にcommitしているので、その当時のzipだと思います。ですので2013/4/11のものと思われます。
3. ごめんなさい。内容については理解していないです。
Thank you!

**Comment by takagiy** [comment]
I see. Thank you for your help!
